
# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# See docs at https://www.packer.io/docs/install/index.html
tags: [karate]
options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/kubectl
  entrypoint: bash
  args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      gcloud container clusters get-credentials ${_CLUSTER_INFO} --zone ${_REGION_INFO} --project ${_GKE_PROJ_NAME} --internal-ip
      kubectl config set-context --current --namespace=${_NAMESPACE_INFO}
      kubectl get job -n ${_NAMESPACE_INFO} | awk 'NR>1{print $1}'
      for pod in $(kubectl get job -n ${_NAMESPACE_INFO} | awk 'NR>1{print $1}'); do
        if [[ "$pod" ==  ${_JOB_NAME} ]]; then
          echo "The JOB ${_JOB_NAME} exists and deleting"  # Job name found a match
          kubectl delete job ${_JOB_NAME} -n ${_NAMESPACE_INFO}
          sleep 30
        fi
      done
      cat ${_API_TEST_PATH}/karate-deployment-new.yaml
      kubectl apply -f ${_API_TEST_PATH}/karate-deployment-new.yaml -n ${_NAMESPACE_INFO}
      sleep 30
      pod_name=`kubectl get pods -l job-name=${_JOB_NAME}  --no-headers -o custom-columns=":metadata.name" -n ${_NAMESPACE_INFO}`
      echo "The pod name is $pod_name."
      counter=0
      while [ $counter -lt 200 ]
      do
        job_status=`kubectl get pods -l job-name=${_JOB_NAME}  --no-headers -o custom-columns=":status.phase" -n ${_NAMESPACE_INFO}`
        echo "The job status of the pod is $job_status."
        if [ "$job_status" == "Pending" ]
        then
            echo "Testing is Initialising, Time is: `date`"
            sleep 10
            continue
        elif [ "$job_status" == "Running" ]
        then
            echo "Testing is in Progress, Time is: `date`"
            sleep 20
            continue
        elif [ "$job_status" == "Succeeded" ]
        then
            sleep 20
            kubectl logs -f $pod_name -n ${_NAMESPACE_INFO}
            echo "Testing is Completed, Time is: `date`"
            exit 0
        elif [ "$job_status" == "Failed" ]
        then
            sleep 20
            kubectl logs -f $pod_name -n ${_NAMESPACE_INFO} 
            echo "Testing Failed Time is: `date`"
            exit 1
        elif [ "$job_status" == "Unknown" ]
        then
            sleep 20
            echo "The job status is Unknown"
            kubectl logs -f $pod_name -n ${_NAMESPACE_INFO} 
            exit 1
        fi
        counter=$(( $counter + 1))
      done
serviceAccount: 'projects/${_GCP_PROJECT_ID}/serviceAccounts/cicd-service-account@${_GCP_PROJECT_ID}.iam.gserviceaccount.com'